In [1]:
import pandas as pd

baseline = pd.read_csv("../results/features_baseline.csv")
baseline

,img_id,patient_id,cancer,asymmetry,border,texture,h_mean,s_mean,v_mean,h_std,s_std,v_std,color_entropy
0,PAT_1549_1882_230.png,PAT_1549,0,0.074175,1.160264,232.973810,0.078980,0.163828,0.444545,0.045501,0.076472,0.212989,1.150426
1,PAT_636_1204_521.png,PAT_636,1,0.163275,1.767430,101.348244,0.083422,0.427045,0.435360,0.176742,0.118168,0.150220,0.690149
2,PAT_778_1471_835.png,PAT_778,1,0.114550,1.146527,89.487607,0.042244,0.421480,0.590572,0.005822,0.050617,0.104417,0.211296
3,PAT_1545_1867_547.png,PAT_1545,0,0.165250,1.595825,73.645748,0.505683,0.498481,0.530819,0.310665,0.059727,0.126687,1.007037
4,PAT_684_1302_588.png,PAT_684,1,0.118025,1.195607,60.731988,0.416340,0.401328,0.513414,0.337568,0.060594,0.078922,0.980623
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098,PAT_279_430_356.png,PAT_279,0,0.116325,1.190750,171.560001,0.053012,0.456649,0.620488,0.152304,0.112835,0.174325,0.272902
2099,PAT_739_1398_331.png,PAT_739,0,0.237125,1.284300,58.167960,0.034566,0.388816,0.416060,0.114214,0.064931,0.107880,0.199132
2100,PAT_192_884_310.png,PAT_192,0,0.793400,2.761158,103.429056,0.144352,0.182462,0.618037,0.265772,0.048517,0.108141,0.619026
2101,PAT_46_880_140.png,PAT_46,1,0.138125,1.352481,60.300169,0.620025,0.370609,0.587091,0.182645,0.077716,0.065489,0.466122
2102,PAT_754_1429_380.png,PAT_754,1,0.124050,1.224961,92.217686,0.067701,0.300411,0.447755,0.057691,0.124854,0.137759,0.856058

In [3]:
extended = pd.read_csv("../results/features_extended.csv")
extended

,img_id,patient_id,hair_coverage,cancer,asymmetry,border,texture,h_mean,s_mean,v_mean,h_std,s_std,v_std,color_entropy
0,PAT_1549_1882_230.png,PAT_1549,0.532986,0,0.074175,1.160264,142.711652,0.083235,0.137094,0.513427,0.047649,0.073780,0.206998,1.205210
1,PAT_778_1471_835.png,PAT_778,0.676240,1,0.114550,1.146527,76.402846,0.042571,0.393829,0.672075,0.005664,0.053805,0.105660,0.211296
2,PAT_1545_1867_547.png,PAT_1545,0.199202,0,0.165250,1.595825,65.871228,0.506633,0.491377,0.534394,0.310196,0.059146,0.126782,1.017493
3,PAT_636_1204_521.png,PAT_636,0.263348,1,0.163275,1.767430,88.661798,0.083318,0.375340,0.452063,0.175014,0.121061,0.168538,0.720295
4,PAT_684_1302_588.png,PAT_684,0.042157,1,0.118025,1.195607,54.160232,0.417005,0.399196,0.505759,0.337509,0.058922,0.072242,0.986412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098,PAT_279_430_356.png,PAT_279,0.349638,0,0.116325,1.190750,169.528379,0.049028,0.431529,0.637154,0.143103,0.108404,0.167954,0.251180
2099,PAT_192_884_310.png,PAT_192,0.018358,0,0.793400,2.761158,99.770209,0.143789,0.181663,0.618468,0.265322,0.048069,0.104194,0.618326
2100,PAT_46_880_140.png,PAT_46,0.006873,1,0.138125,1.352481,60.032623,0.620053,0.370090,0.586558,0.182617,0.077348,0.064733,0.467386
2101,PAT_2140_4726_85.png,PAT_2140,0.449052,0,0.317350,5.042212,166.721935,0.093746,0.414367,0.771606,0.212021,0.115484,0.140102,0.435669
2102,PAT_754_1429_380.png,PAT_754,0.007678,1,0.124050,1.224961,91.433174,0.067707,0.300224,0.447848,0.057685,0.124812,0.137309,0.856136